apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cc-ingress
  namespace: cc-frontend
spec:
  ingressClassName: nginx
  rules:
  - host: hambining.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cc-nginx-svc
            port:
              number: 80
