apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cc-tomcat-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hambining/check-argoCD'
    targetRevision: HEAD
    path: manifests/tomcat
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cc-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
