apiVersion: v1
kind: ConfigMap
metadata:
  name: cc-nginx-configmap
  namespace: cc-frontend
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://cc-tomcat-svc.cc-backend.svc.cluster.local:8080/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header Cookie $http_cookie;

            proxy_pass_header Set-Cookie;
            proxy_cookie_path / /;
            proxy_buffering off;
        }
    }
